### ISSUE TITLE
"Database error:" logged when trying to access web UI

### ISSUE THREAD

**Issue by joncodis** [sensepost/Snoopy#2]
Hi Glenn,
I'm working on getting your cool project setup using Raspberry Pi devices for the WiFi sensors.  For the Snoopy server, I have set up a VM running Ubuntu 12.04 LTS 32bit, as per your notes in the server setup. I'm getting probe data, am seeing wigle activity, and see streetview images being saved under "web_data", so it looks like things are working. When I access the web ui however, I only  get the boxes with the mac addresses for the title, but with no content inside the boxes.  In the snoopy.log file, I see errors scroll by on each click of the mouse as I try to refresh the view.  Please see a snapshot of errors I am seeing below and let me know if you wish me to send the full log for close inspection.

Any ideas?

Thanks!

Jon

2013-04-29 17:03:53 ERROR **init**.py: Database error:
  File "/home/woodstock/snoopy/server/bin/snoopy/src/snoopy/plugins/wigle.py", line 13, in wigle
    db.Probe.probe_ssid == db.Wigle.ssid

TypeError('<lambda>() takes exactly 2 arguments (3 given)',)
2013-04-29 17:03:53 ERROR app.py: Exception on /client/data/get [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1504, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1264, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1262, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1248, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/woodstock/snoopy/server/bin/snoopy/src/snoopy/web/**init**.py", line 14, in decorated_function
    return f(_args, *_kwargs)
  File "/home/woodstock/snoopy/server/bin/snoopy/src/snoopy/web/main.py", line 98, in client_data_get
    cldata[options['name']] = dict(title=options['title'], data=fn(mac))
  File "/home/woodstock/snoopy/server/bin/snoopy/src/snoopy/plugins/wigle.py", line 13, in wigle
    db.Probe.probe_ssid == db.Wigle.ssid
TypeError: <lambda>() takes exactly 2 arguments (3 given)
2013-04-29 17:03:53 INFO _internal.py: 192.168.1.107 - - [29/Apr/2013 17:03:53] "POST /client/data/get HTTP/1.1" 500 -
2013-04-29 17:03:53 INFO _internal.py: 192.168.1.107 - - [29/Apr/2013 17:03:53] "GET /static/css/images/ui-icons_cccccc_256x240.png HTTP/1.1" 200 -

**Comment by xeroxnir** [comment]
I have the same problem, no idea how to solve it...

**Comment by ghost** [comment]
I addressed the issue in my pull request. Try "pip uninstall requests" and then "pip install requests==0.14.2" 

You will probably encounter a couple other issues that I have addressed as well, so if you encounter a problem you can check out my fork.
