### ISSUE TITLE
Errno 13

### ISSUE THREAD

**Issue by toughbunny** [sensepost/Snoopy#4]
Hi,

I installed snoopy on a web-based vm on koding.com, which is both 64-bit and not the recommended version of ubuntu (13), so I knew that this would lead to problems. However, since the install, I am not able to do much with the menus because it keeps aborting my commands with errno 13 permission denied, including just starting the server on managing drone configuration packs.

Thanks!

**Comment by toughbunny** [comment]
Hi,

Here is an update with pictures. I forgot to add that when I use sudo, I just get a blank screen like in the last picture.

![snoopy2](https://cloud.githubusercontent.com/assets/6821011/2540266/2e8661aa-b5d1-11e3-948d-9fc80cd64032.png)
![snoopy1](https://cloud.githubusercontent.com/assets/6821011/2540269/321d3938-b5d1-11e3-91a7-17518c4c224a.png)
![snoopy](https://cloud.githubusercontent.com/assets/6821011/2540271/35446ce4-b5d1-11e3-8801-6f609cae28f7.png)
![blank screen](https://cloud.githubusercontent.com/assets/6821011/2540274/3919e1fa-b5d1-11e3-8414-24d774bbbcc3.png)

**Comment by sensepost** [comment]
It looks like the file permissions/ownership on the file ./bin/wigle_credentials.txt do not allow you to write to it.

Rogan

On 27 March 2014 19:00:09 SAST, toughbunny notifications@github.com wrote:

> Hi,
> 
> Here is an update with pictures. I forgot to add that when I use sudo,
> I just get a blank screen like in the last picture.
> 
> ![snoopy2](https://cloud.githubusercontent.com/assets/6821011/2540266/2e8661aa-b5d1-11e3-948d-9fc80cd64032.png)
> ![snoopy1](https://cloud.githubusercontent.com/assets/6821011/2540269/321d3938-b5d1-11e3-91a7-17518c4c224a.png)
> ![snoopy](https://cloud.githubusercontent.com/assets/6821011/2540271/35446ce4-b5d1-11e3-8801-6f609cae28f7.png)
> ![blank
> screen](https://cloud.githubusercontent.com/assets/6821011/2540274/3919e1fa-b5d1-11e3-8414-24d774bbbcc3.png)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sensepost/Snoopy/issues/4#issuecomment-38831019

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by toughbunny** [comment]
Thanks,
But now I have another problem. I fixed the permissions for the two files, wigle_creds and openvpn-status.log files, and all the other files in the /home/woodstock/snoopy/server/bin directory. Now when I type snoopy, I just get a blank screen like in the last picture. 

Thanks!

**Comment by toughbunny** [comment]
Sorry,

I forgot to add that when I scroll up from the blank screen, I see the following error:

^CTraceback (most recent call last):
  File "bin/vpn_drones.py", line 14, in <module>
    line=f.readline()
KeyboardInterrupt

**\* Ouch! Exiting ***

**Comment by toughbunny** [comment]
Sorry again,

This time I left the command running for longer before interrupting and got:

^CTraceback (most recent call last):
  File "bin/vpn_drones.py", line 13, in <module>
    while ( not re.search('^Common.*',line)):
  File "/usr/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python2.7/re.py", line 229, in _compile
    p = _cache.get(cachekey)
KeyboardInterrupt

**\* Ouch! Exiting ***

Thanks Again

**Comment by matznerd** [comment]
Just don't use koding. Try it on a digitalocean droplet with at leat 1gb of ram and see if the problems persist.

**Comment by toughbunny** [comment]
Hi,

Thanks Matznerd, but koding is free and you have to pay for digitalocean. Also, there has to be some traceable error here. I would like to keep on trying with koding.

Thanks!

**Comment by toughbunny** [comment]
Hi, I just wanted to say that I've isolated the problem. When I don't give read permissions to /etc/openvpn/openvpn-status.log, the the command to start snoopy server components from the server menu, it stops the server right after with a permissions denied error. But when I do give read permissions, the command snoopy just returns a blank screen.

Thanks!
